version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "ItemDatabase"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/ItemDatabase

volumes:
  db_data:
